version: '3'
services:
  postgis:
    image: mdillon/postgis
    environment:
    - POSTGRES_USER=fastlanes
    - POSTGRES_PASSWORD=1234
    - POSTGRES_DB=fastlanes
    volumes:
       - ./data/postgres:/var/lib/postgresql/data
    ports:
     - "5434:5432"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5434"]
      interval: 30s
      timeout: 10s
      retries: 20
  db:
    build:
      context: .
      dockerfile: DockerfileDB
    ports:
     - "3001:3001"
    environment:
    - DATABSE_URL=postgresql+psycopg2://fastlanes:1234@postgis:5432/fastlanes
    - SHOULD_DROP_ALL_TABELS=1
    - GTFS_FILE_PATH=DB/raw_data/small_mock.zip
    - PASSENGER_COUNT_FILE_PATH=DB/raw_data/passenger_count.csv
    - SHOULD_LOAD_GTFS_DATA=1
    - SHOULD_PASSENGER_LOAD_DATA=0
    - SHOULD_OVERWRITE_ZIP_FILES=1
    depends_on:
      - postgis
    restart: on-failure
  dp:
    build:
      context: .
      dockerfile: DockerfileDP
    ports:
     - "3002:3002"
  ui:
    build:
      context: .
      dockerfile: UI/Dockerfile
    ports:
     - "8080:8080"
