version: '3'
services:
  postgis:
    image: mdillon/postgis
    environment:
    - POSTGRES_USER=fastlanes
    - POSTGRES_PASS=1234
    - POSTGRES_DBNAME=fastlanes
    - ALLOW_IP_RANGE=0.0.0.0/0
    volumes:
      - data-volume:/var/lib/db
  db:
    build:
      context: https://github.com/arnonkahani/FastLane.git
      dockerfile: DB/Dockerfile
    ports:
     - "3001:3001"
  dp:
    build:
      context: https://github.com/arnonkahani/FastLane.git
      dockerfile: DockerfileDP
    ports:
     - "3002:3002"
  ui:
    build:
      context: https://github.com/arnonkahani/FastLane.git/UI
      dockerfile: Dockerfile
    ports:
     - "8080:8080"