version: '3'
services:
  postgis:
    image: mdillon/postgis
    environment:
    - POSTGRES_USER=fastlanes
    - POSTGRES_PASSWORD=1234
    - POSTGRES_DB=fastlanes
    volumes:
       - ./data/postgres:/var/lib/postgresql/data
    ports:
     - "5433:5432"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5433"]
      interval: 30s
      timeout: 10s
      retries: 5
  db:
    build:
      context: https://github.com/arnonkahani/FastLane.git
      dockerfile: DockerfileDB
    ports:
     - "3001:3001"
    depends_on:
      - postgis
    restart: on-failure
    network_mode: "host"
  dp:
    build:
      context: https://github.com/arnonkahani/FastLane.git
      dockerfile: DockerfileDP
    ports:
     - "3002:3002"
  ui:
    build:
      context: https://github.com/arnonkahani/FastLane.git
      dockerfile: UI/Dockerfile
    ports:
     - "8080:8080"